name: Codex Scribe Commit

on:
  workflow_dispatch:
    inputs:
      file_path:
        description: "Path to write (e.g., Echo_Mirror_Drive/historic_milestones/2025-08-21_first_sprint_of_the_machine.md)"
        required: true
      content_b64:
        description: "Base64-encoded UTF-8 content for the file"
        required: true
      commit_message:
        description: "Commit message"
        required: true

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CDEX_PAT }}   # uses the secret you just added
      - name: Write file
        shell: bash
        run: |
          mkdir -p "$(dirname "${{ inputs.file_path }}")"
          echo "${{ inputs.content_b64 }}" | base64 -d > "${{ inputs.file_path }}"
      - name: Commit & push
        shell: bash
        run: |
          git config user.name "Codex Scribe"
          git config user.email "codex-scribe@users.noreply.github.com"
          git add "${{ inputs.file_path }}"
          git commit -m "${{ inputs.commit_message }}"
          git push
